fix: Scope down create tag permissions
lacework/terraform-aws-agentless-scanning pull request #108
Opened 2023-10-11 05:05 UTC by jacobkilby

## Summary

This fixes https://lacework.atlassian.net/browse/RAIN-75027. This changes our terraform to follow best practices and further scope down the permission KmsGrant to only allow use on AWS resources.

Issue
https://lacework.atlassian.net/browse/RAIN-75027

## How did you test this change?

How did you test this change?
I made this change in a local version of our Terraform provider and created a new agentless integration with it, confirming that scans still run and succeed as expected. 

## Issue
https://lacework.atlassian.net/browse/RAIN-75027

2023-10-11 14:00 UTC, theopolis approved these changes

2023-10-11 14:00 UTC, theopolis commented on main.tf
> +          Sid = "CreateTags"
```suggestion
          Sid = "CreateSnapshotTags"
```

2023-10-12 01:08 UTC, theopolis requested changes
Sorry, missed this before. Unsure if this is functionally different, but using the `=` is consistent with the rest of the policies.

2023-10-12 01:08 UTC, theopolis commented on main.tf
> +                "ec2:CreateAction": "CreateSnapshot"
```suggestion
                "ec2:CreateAction" = "CreateSnapshot"
```

2023-10-12 01:11 UTC, jacobkilby commented on main.tf
> +                "ec2:CreateAction": "CreateSnapshot"
good catch thank you, fixed

2023-10-12 01:18 UTC, theopolis approved these changes

2023-10-19 19:03 UTC, theopolis commented
I have this change deployed and I am running several end to end automated tests to build more confidence.

2023-10-19 21:08 UTC, merged