feat: Allow the user to pass additional custom environment variables …
lacework/terraform-aws-agentless-scanning pull request #60
Opened 2023-03-01 17:30 UTC by bebold-jhr

…to the ECS task

In addition the the environment variables which are defined by the module already, the user can add additional environment variables.

## Summary

In our setup we don't have an internet gateway. The whole communication is done via transit gateway, direct connect and an on-prem proxy. So we would like to be able to set additional environment variables.

## How did you test this change?

I created a minimal setup to test this:

```hcl
terraform {
  required_providers {
  }
}

locals {
  initial = [
    {
      name  = "STARTUP_PROVIDER"
      value = "AWS"
    },
    {
      name  = "STARTUP_RUNMODE"
      value = "TASK"
    },
    {
      name  = "LOCAL_STORAGE"
      value = "/tmp"
    },
    {
      name  = "STARTUP_SERVICE"
      value = "ORCHESTRATE"
    },
  ]

  merged = setunion(local.initial, var.custom)
}

variable "custom" {
  type = list(object({
    name = string
    value = string
  }))

  default = [
    {
      name = "HTTP_PROXY"
      value = "127.0.0.1"
    }
  ]
}

output "output" {
  value = local.merged
}
```
## Issue

2023-03-01 20:51 UTC, theopolis commented
I like the flexibility of this but what about an alternative of having explicit http_proxy variables for the module? Then those would set the appropriate environment variables.

2023-03-02 07:47 UTC, bebold-jhr commented
Hi @theopolis,
thank you for your fast feedback.

I guess this comes down to some questions. How likely is it that one wants to set other environment variables apart from the proxy? And if so how many cases could you cover using explicit variables until it unnecessarily bloats the API?

Another question would be: What could the explicit proxy config look like and does it have a good fit?

From what I know there are three env variables that we have to take into consideration: `http_proxy`, `https_proxy`, `no_proxy`. Sadly enough it seems that depending on the application these three are either expected to be in upper or in lowercase. So worst case would be six environment variables. The module can handle this for us. However, the question of whether a more general approach or an explicit proxy configuration is more appropriate raises the question of whether the module should handle this logic.

Here are the two options for the API that I see:

**One:** One variable each.
```hcl
variable "http_proxy" {
  type = string
}

variable "https_proxy" {
  type = string
}

variable "no_proxy" {
  type = string
}
```

**Two:** Object
```hcl
variable "proxy" {
  type = object({
    http_proxy = string
    https_proxy = string
    no_proxy = string
  })
}
```

My preference would be the second version, because the properties, which build up a proxy configuration are coupled together and the numer of additional properties for module is reduced.

I guess that the downside would be that the code gets a little bit more complex when using explicit proxy config, because I would check if I have to pass each environment variable or not.

I could offer to create a different PR for an explicit proxy configuration in order to compare both.

2023-03-02 19:50 UTC, theopolis commented
Thank you so much for flushing that out.

> How likely is it that one wants to set other environment variables apart from the proxy?

Good question. There are none right now but I can see this being a good API for exposing advanced behavior.

> And if so how many cases could you cover using explicit variables until it unnecessarily bloats the API?

Another good call out, but I also like the 'self-documenting' feature of having the variables also communicate what is possible. There's a good chance someone will see the proxy related variables and immediately answer questions they have as to if this does/does-not support setting proxies.

Based on your suggestion I do like the second variation where the config is an object.

One other "pro" for using a terraform variable is that it feels more future-proof. Meaning that in the future if the way to set the proxy within the scanner application changes, then we can handle that adaption within the terraform logic. One example would be switching the deployment away from ECS and onto something that does not support setting environment variable directly, where we might have to set settings via tags or an input yaml/etc.

> I could offer to create a different PR for an explicit proxy configuration in order to compare both.

Thanks for the offer but I am happy to take this action item of setting up the proxy configuration as an explicit option. In the mean time we can apply both of these approaches. I see the advantage of always maintaining this advanced configuration of setting environment variables on the task.

2023-03-02 19:52 UTC, theopolis requested changes
Two quick nitpicks to the naming to make it clear this variable is optional/additional.

2023-03-02 19:52 UTC, theopolis commented on variables.tf
> +variable "environment_variables" {
```suggestion
variable "additional_task_environment_variables" {
```

2023-03-02 19:52 UTC, theopolis commented on variables.tf
> +  description = "List of environment variables passed to the ECS task."
```suggestion
  description = "Optional list of additional environment variables passed to the ECS task."
```

2023-03-02 20:31 UTC, bebold-jhr commented on variables.tf
> +variable "environment_variables" {
Renamed it accordingly.

2023-03-02 20:31 UTC, bebold-jhr commented on variables.tf
> +  description = "List of environment variables passed to the ECS task."
Adjusted description accordingly.

2023-03-02 20:45 UTC, bebold-jhr commented
Hi @theopolis,

thanks again for the fast feedback.

> Another good call out, but I also like the 'self-documenting' feature of having the variables also communicate what is possible. There's a good chance someone will see the proxy related variables and immediately answer questions they have as to if this does/does-not support setting proxies.

Very good argument. I like that.

> One other "pro" for using a terraform variable is that it feels more future-proof. Meaning that in the future if the way to set the proxy within the scanner application changes, then we can handle that adaption within the terraform logic. One example would be switching the deployment away from ECS and onto something that does not support setting environment variable directly, where we might have to set settings via tags or an input yaml/etc.

I see your point. Initially I was also thinking about whether this leaks too much implementation detail or not.

> Thanks for the offer but I am happy to take this action item of setting up the proxy configuration as an explicit option. In the mean time we can apply both of these approaches. I see the advantage of always maintaining this advanced configuration of setting environment variables on the task.

Okay great. I'm glad if this change can still further improve the module. In case you are short on time just let me know. I'd be happy to assist you with the explicit proxy change.

2023-03-03 14:32 UTC, theopolis approved these changes

2023-03-03 14:35 UTC, theopolis commented
Thanks @bebold-jhr, this looks good to go! One last request (sorry for the overhead) but can you amend/sign/force-push the commit as we have branch protections requiring all commits to be signed:

```
git commit --amend -S
git push -f
```

Here are the two relevant GitHub links for guidance:
- https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key
- https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

2023-03-03 19:25 UTC, bebold-jhr commented
No problem, it's done.

2023-03-05 22:29 UTC, merged